#!/usr/bin/env ruby
require 'pry'

#CLASSES DEFINED HERE

class Fileq #Class that deals with file and its modification

	def initFile #Sets up variable for array of questions, functions kinda like a clipboard?
		@questions = []
		@listNum = 1
	end

	def see #Displays questions numbering by element number
		@questions.each do |question|
			puts "#{@listNum}.#{question}"
			@listNum += 1
		end
	end
	
	def getQuestions #Opens the file line by line and calls on loadFile
		File.open("/Users/spencer/code/questions/questions.txt", "r") do |f|
				loadFile(f)
			f.close
		end	
	end

	def loadFile(part) #Takes current line and saves it as an item in the question array
		while line = part.gets
				@questions.push(line.split("\n").join())
		end
	end

	def removeQuestion(listPos)	#Takes a number corresponding to display list number and deletes it
		@questions -= [@questions[listPos.to_i - 1]]
	end
	
	def addQuestion(newQuestion) #Pushes new questions to question array
		@questions.push(newQuestion)
	end

	def saveFile #Empties .txt and fills back up with the question array
		File.open("/Users/spencer/code/questions/questions.txt", "w") do |f|
			f.puts @questions
			f.close
		end
	end
end

class Commands #Class that gets argument variables, analyzes them, and passes them to fileq class

	def initAndExe #Sets up values and calls for the initialization of fileq class
		@argument = ARGV
		@questionList
		initQuestionClass
		argumentReader
	end

	def initQuestionClass #Initializes fileq class and calls fileq to set up questions
		@questionList = Fileq.new
		@questionList.initFile
		@questionList.getQuestions
	end

	def argumentReader #Reads the argument variable and decides what to do
		if @argument[0].to_s == "" 
			show
		elsif @argument[0] == "add" and @argument[1].to_s != ""
			add(@argument[1])
		elsif @argument[0] == "rm" and @argument[1].to_i > 0
			rm(@argument[1])
		elsif @argument[0] == ("help")
			help
		else
			puts "error: (invalid argument)\nenter 'help' for a list of valid arguments"
		end
		
	end

	def help #Prints a help sheet
		puts "Valid arguments for 'questions'\n------------------------------\n"
		puts "- add ('question')    => Adds a question with the questions in quotes after it.\n\n"
		puts "- rm (list number)    => Removes a questions from the list with that number.\n\n"
		puts "-                     => No argument will print the list."
	end

	def show #Calls fileq class to display questions
		@questionList.see
	end

	def add(string) #Passes the question, from argv, to be added to the fileq class
		@questionList.addQuestion(string)
		@questionList.see
		@questionList.saveFile
	end

	def rm(position) #Passes the postiton, from argv, to remove from the fileq class
		@questionList.removeQuestion(position)
		@questionList.see
		@questionList.saveFile
	end
end

class Gateway #Class that decides if argv is sufficient to run rest of code
	def run
		puts "\n"
		checkLegit_ness
		puts "\n"
	end

	def checkLegit_ness
		if ARGV.length > 2
			puts "error"
		else
			runCode
		end
	end
		
	def runCode
		commandArg = Commands.new 
		commandArg.initAndExe
	end
end

#CODE EXECUTION HERE

start = Gateway.new
start.run